# Generated by Django 4.1.4 on 2022-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.PositiveIntegerField(),
        ),
    ]
