# Generated by Django 4.1.4 on 2022-12-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='dstrict',
            new_name='district',
        ),
    ]
