# Generated by Django 4.1.4 on 2022-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_category_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_duration',
            field=models.PositiveIntegerField(),
        ),
    ]
