# Generated by Django 4.1.4 on 2022-12-19 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_item_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="rating",
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
