# Generated by Django 4.1.4 on 2022-12-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_category_options_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
